[package]
name = "kperf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kperf-sys = "0.0.3"
thiserror = "1.0.58"

[dev-dependencies]
anyhow = { version = "1.0.81", features = ["backtrace"] }
